<?php
/**
 * Created by MarxMedia.
 * Author: Kevin Marques
 * Date: 18/07/2018 - 09:03
 * Grh : NewUser.module
 */

namespace Modules\Application\Users\GraphicInterface;


use Interfaces\ThrowableAll;

use Modules\System;
use Modules\Template\Template;

class Create
{
    private $moduleName;

    private function getModuleName() { return $this->moduleName; }
    public function setModuleName($moduleName) { $this->moduleName = $moduleName; }
    public function __construct($moduleName) {
        $this->setModuleName($moduleName);
    }
    public function init(){
        try{
            $Parser = [];
            $Parser['title_user'] = _tr('new_user');
            $Parser['value_name'] ='';
            $Parser['value_lastname'] ='';
            $Parser['value_email'] ='""';
            $Parser['value_email_alt'] ='""';
            $Parser['value_login'] ='';
            $Parser['value_password'] ='';
            $Parser['pass_red_in_edit'] = '';
            $Parser['link_back'] = WWW_PATH.$this->getModuleName().DS;

            //Dados para Ativação de Data-send
            $dataSendPost = [];
            $dataSendPost['url'] = _system.$this->getModuleName().DS.'new'.DS.System::getAccessToken();
            $dataSendPost['method'] = 'POST';
            $Parser['datasend'] = 'data-send="'.base64_encode(json_encode($dataSendPost)).'"';

            $templateNew = new Template(APP_ROOT.DS.MODULES_PATH.DS.$this->getModuleName().DS."Gui/Views/formUser.tpl",$Parser,true);
            echo $templateNew->showTemplate();
        }
        catch (ThrowableAll $e){
            echo $e->getMessage();
        }

    }
}