<?php
/**
 * Created by MarxMedia.
 * Author: Kevin Marques
 * Date: 17/07/2018 - 21:52
 * Grh : HomeUsers.module
 */

namespace Modules\Application\Users\GraphicInterface;


use Interfaces\ThrowableAll;
use Modules\CNN;
use Modules\Pagination;
use Modules\System;
use Modules\Template\Template;
class Home
{
    private $sql;
    private $moduleName;

    private function getModuleName() { return $this->moduleName; }
    private function getSql() { return $this->sql; }
    public function __construct($ModuleName) {
        $this->sql = CNN::getSql();
        $this->moduleName = $ModuleName;
        try{
            $this->sql = CNN::getSql();
            $JsonParser =[];
            $DataParser=[];

            $DataParser['data_table'] = '';
            //
            $getUserGroups = $this->getSql()->query("SELECT * FROM ".__USERS." WHERE status!='4'");

            if($getUserGroups->rowCount() > 0){
                //Variavel de cabeçalho de tabela
                $tableHeadData = [];
                $tableHeadData['data_table'] ='';
                //Recupera o template de TR para inserção na tabela
                $pagination = new Pagination();
                $pagination->setDefinitions([
                    "limit"=> 5,
                    "page" => _level1,
                    "link" => WWW_PATH . $this->getModuleName()
                ]);
                $pagination->setContent($getUserGroups->fetchAll(\PDO::FETCH_ASSOC));
                foreach ($pagination->getContent() as $tableLine){
                    $preLink = WWW_PATH.$ModuleName.DS;
                    //Data de ativação de usuário ou bloqueio pelo switch na table
                    $dataSendActiveUser =[];
                    $dataSendActiveUser['url'] = _system.DS.$this->getModuleName().DS.'activeUser'.DS.$tableLine['authid'].DS.System::getAccessToken();
                    $dataSendActiveUser['method'] = "GET";
                    $dataSendActiveUser['typeAction'] = 'mark';
                    $dataSendActiveUserJSON = 'data-send="'.base64_encode(json_encode($dataSendActiveUser)).'"';
                    //Data Parser de tratamento
                    $lineTable = [];

                    $lineTable['name'] = $tableLine['name'];
                    $lineTable['login'] = $tableLine['login'];
                    $lineTable['email'] = $tableLine['email'];
                    $lineTable['link_edit'] = $preLink.'edit'.DS.$tableLine['authid'];
                    $lineTable['data_send_active_user'] = $dataSendActiveUserJSON;
                    $lineTable['authid'] = $tableLine['authid'];
                    if($tableLine['status'] == 1){
                        $checkStatus = "checked='checked'";
                    }
                    else if($tableLine['status'] == 4){
                        $checkStatus = "checked='checked'";
                    }
                    else{
                        $checkStatus ='';
                    }
                    $lineTable['checked_active'] = $checkStatus;
                    $dataPrompt = [];
                    $dataPrompt['url'] = _system.DS.$ModuleName.DS.'get'.DS.$tableLine['authid'].DS.System::getAccessToken();
                    $dataPrompt['method'] = "GET";
                    $lineTable['data_prompt'] =base64_encode(json_encode($dataPrompt));
                    $tempTr = new Template(APP_ROOT.DS.MODULES_PATH.DS.$ModuleName.DS."Gui/Views/Controller/tableListUsers.tpl",$lineTable,true);
                    $tableHeadData['data_table'] .= $tempTr->showTemplate();


                }
                $tableHeadData['pagination'] = $pagination->getInterface();
                //Template de cabeçalho e estrutura de tabela
                $TableHeader = new Template(APP_ROOT.DS.MODULES_PATH.DS.$ModuleName.DS."Gui/Views/Controller/tableUsers.tpl",$tableHeadData,true);
                //Composição de Template principal da página
                $DataParser['composition'] =$TableHeader->showTemplate();
            }
            else{
                $tableMessage = [];
                $tableMessage['title'] = _tr('no_user_registered');
                $tableMessage['msg'] = _tr('none_one_user_is_register_on_your_system_please_add_one');
                $tableMessage['icon'] = 'ais-info';
                $TableNothing = new Template(APP_ROOT.DS.MODULES_PATH.DS.$ModuleName.DS."Gui/Views/Controller/tableNoContent.tpl",$tableMessage,true);
                $DataParser['composition'] = $TableNothing->showTemplate();
            }
            $DataParser['link_new'] = WWW_PATH.$ModuleName."/new/";
            //Template principal da página
            $Template = new Template(APP_ROOT.DS.MODULES_PATH.DS.$ModuleName.DS."Gui/Views/basic.tpl",$DataParser,true);
            echo $Template->showTemplate();
        }
        catch (ThrowableAll $exception){
            Upshot::showData("Excessão",null,$exception->getMessage(),'',null,true);
        }
    }
}