<?php
/**
 * Created by MarxMedia.
 * Author: Kevin Marques
 * Date: 14/07/2018 - 19:04
 * Grh : DelGroup.module
 */

namespace Modules\Application\Products\Manager;


use Interfaces\ThrowableAll;
use Modules\CNN;
use Modules\System;

class Del
{
    private $accessToken;
    private $cidToRemove;
    private $sql;
    private $moduleName;

    public function setModuleName($moduleName) { $this->moduleName = $moduleName; }

    public function getModuleName() { return $this->moduleName; }
    public function setAccessToken($accessToken) { $this->accessToken = $accessToken; }
    public function setPrdidToRemove($prdidToRemove) { $this->prdidToRemove = $prdidToRemove; }
    private function getPrdidToRemove() { return $this->prdidToRemove; }
    private function getAccessToken() { return $this->accessToken; }

    public function getSql(): \PDO { return $this->sql; }
    public function __construct() {
        $this->sql= CNN::getSql();
    }
    public function remove(){
        try{
            if(null == $this->getPrdidToRemove()){
                System::message('error',_tr("Remover produto"),_tr("'Produto não encontrado."));
            }
            else if(System::getAccessToken() != $this->getAccessToken()){
                System::message('error',_tr("Remover produto"),_tr("Recebimento de token de acesso está errado."));
            }
            else{
                !defined("_AUTHID") ? define("_AUTHID",$_SESSION['authid']) : null;
                $getCover = $this->getSql()->prepare("SELECT * FROM products WHERE prdid=?");
                $getCover->bindValue(1,$this->getPrdidToRemove());
                $getCover->execute();
                $fetchCover = $getCover->fetch(\PDO::FETCH_ASSOC);
                if($getCover->rowCount() == 0){
                    System::message('error',_tr("Remover produto"),_tr("Produto não cadastrado."));
                }
              //  else if($fetchCover['authid'] == _AUTHID){
                //    System::message('error',_tr('remove_credential'),_tr('you_cannot_remove_credential_that_you_are_using'));
                //}
                else{
                    $remove = $this->getSql()->prepare("DELETE FROM products WHERE prdid=?");
                    $remove->bindValue(1,$this->getPrdidToRemove());
                    $remove->execute();

                    if($remove){
                        System::message('success',_tr("Remover produto"),_tr("Produto removido com sucesso!"),System::goTo(WWW_PATH."Products",1));
                    }
                    else{
                       System::message('warning',_tr("Remover produto"),_tr("Impossível remover o produto!"));
                    }
                }
            }
        }
        catch (ThrowableAll $e){
            System::message('error',_tr('internal_error'),$e->getMessage());
        }
    }
}