<?php
/**
 * Created by MarxMedia Solutions.
 *         Author: Nelson Anjos
 *    Date: 03/2019
 *
 */

namespace Modules\Stock;


use Interfaces\ThrowableAll;
use Modules\CNN;
use Modules\System;
use Modules\Template\Template;

class Modify
{
  private $prdidToEdit;
  private $moduleName;
  private $sql;
  private function getSql(): \PDO { return $this->sql; }
  private function getPrdidToEdit() { return $this->prdidToEdit; }
  private function getModuleName() { return $this->moduleName; }
  public function setPrdidToEdit($prdidToEdit) { $this->prdidToEdit = $prdidToEdit; }
  public function setModuleName($moduleName) { $this->moduleName = $moduleName; }
    public function __construct($ModuleName, $prdid) {
        $this->sql = CNN::getSql();
        $this->setModuleName($ModuleName);
        $this->setPrdidToEdit($prdid);
    }

    public function init(){
        try{
            //Recuperando grupo para edição
            $stock = $this->getSql()->prepare("SELECT * FROM ".__STOCK." WHERE prdid=?");
            $stock->bindValue(1,$this->getPrdidToEdit());
            $stock->execute();
            
            
            $datasend =[];
            $datasend['url'] = _system.DS.$this->getModuleName().DS."edit".DS.$this->getPrdidToEdit().DS.System::getAccessToken();
            $datasend['method'] = "POST";
            
            $Parser = [];
            $Parser['link_back'] = WWW_PATH.$this->getModuleName().DS;
            

            $prdidDefActual = $this->getSql()->prepare("SELECT * FROM ".__PRODUCT." WHERE prdid=?");
            $prdidDefActual->bindValue(1,$this->getPrdidToEdit());
            $prdidDefActual->execute();
            $ftPrdidActual = $prdidDefActual->fetch(\PDO::FETCH_ASSOC);
            //Atribuição de options do select
            $Parser['products_options'] = $ftPrdidActual['name'];
            

            //Default patterns
            $Parser['link_back'] = WWW_PATH.$this->getModuleName().DS;
            $Parser['datasend'] = 'data-send="'.base64_encode(json_encode($datasend)).'"';
            $template = new Template(APP_ROOT.DS.MODULES_PATH.DS.$this->getModuleName().DS."Gui/Views/editStock.tpl",$Parser,true);
            echo $template->showTemplate();
        }
        catch (ThrowableAll $exception){
            echo $exception->getMessage();
        }
      }

    }
