<?php
/**
 * Created by MarxMedia.
 * Author: Kevin Marques
 * Date: 08/07/2018 - 00:53
 * Grh : NewCredentials.modulele
 */

namespace Modules\Application\UserGroup\GraphicInterface;


use Interfaces\ThrowableAll;
use Modules\Application\UserGroup\Manager\ActiveModules;
use Modules\System;
use Modules\Template\Template;

class Create
{
    public function __construct($ModuleName) {
        try{
            $datasend =[];
            $datasend['url'] = _system.DS.$ModuleName.DS."new".DS.System::getAccessToken();
            $datasend['method'] = "POST";
            $Parser = [];
            $Parser['link_back'] = WWW_PATH.$ModuleName.DS;
            $Parser['value_name'] ='';
            $Parser['value_description'] ='';
            $Parser['datasend'] = 'data-send="'.base64_encode(json_encode($datasend)).'"';
            $Parser['title_user_group'] = _tr('new_user_group');
            //----------------------------------------------------------
            $ActiveModules = new ActiveModules();
            $listObj = $ActiveModules->getModulesToShow();
            //==========================================================
            $pointer = 0;
            $position = 0;
            $showObject = '';
            $total = count($listObj);
            foreach ($listObj as $item) {
                //------------------------------
                //Contadores
                $pointer ++;
                $position ++;
                //------------------------------
                //Construtor de Atribuição de Template
                $eachModules = [];
                $eachModules['module_name'] = _tr($item['module_name_translate']);
                $eachModules['id_obj'] = strtolower($item['module']);
                $eachModules['input_name'] = $item['module'];
                $eachModules['checked_v_obj'] = '';
                $eachModules['checked_a_obj'] = '';
                $eachModules['checked_e_obj'] = '';
                $eachModules['checked_d_obj'] = '';
                $eachModules['checked_l_obj'] = '';
                //-----------------------------------
                //Atribuidor de Linha para uma quantidade de iterações
                if($pointer == 1)
                    $row = "<div class='row jc-between'>";
                else
                    $row = '';
                //----------------------------------
                if($position < $total && $pointer == 4 || $position == $total){
                    $rowEnd = "</div>";
                    $pointer = 0;
                }
                else{
                    $rowEnd = '';
                }
                //----------------------------------
                //Aplicação do template de permissoes
                $permissionForEach = new Template(APP_ROOT.DS.MODULES_PATH.DS.$ModuleName.DS."Gui/Views/Controller/controlPermissions.tpl",$eachModules,true);
                $showObject .= $row.$permissionForEach->showTemplate().$rowEnd;

            }
            //Definição do escopo de troca
            $Parser['permissions'] = $showObject;
            //----------------------------------------------------------
            //Atribuidor de template principal
            $template = new Template(APP_ROOT.DS.MODULES_PATH.DS.$ModuleName.DS."Gui/Views/newGroup.tpl",$Parser,true);
            echo $template->showTemplate();
        }
        catch (ThrowableAll $exception){
            echo $exception->getMessage();
        }

    }
}