<?php

namespace Modules\Stock;


use Modules\CNN;
use Modules\System;

class GetData
{
    private $sql;
    private $moduleName;
    public function getSql() { return $this->sql; }
    public function getModuleName() { return $this->moduleName; }
    public function __construct($moduleName) {
        $this->sql = CNN::getSql();
        $this->moduleName = $moduleName;
    }
    public function getData($prdid, $accessToken){
        if(empty($prdid)){
            System::message('error',_tr('get_data'),_tr('group_id_needed_not_found'));
        }
        else if($accessToken != System::getAccessToken()){
            System::message('error',_tr('get_data'),_tr('access_token_receive_is_wrong'));
        }
        else{
            $recoverGroupName = $this->getSql()->prepare("SELECT * FROM see_stocks WHERE prdid=?");
            $recoverGroupName->bindValue(1,$prdid);
            $recoverGroupName->execute();
            $fetchData = $recoverGroupName->fetch(\PDO::FETCH_ASSOC);
            $message = "<div class='txt-center pd-tb-1'>
                            <h3 class='txt-center'>"._tr('warning_stock_will_be_removed')."</h3>
                            <h4>"._tr('product_id').": <b>".$fetchData['prdid']."</b></h4>
                            <span class='block'>"._tr('product_name').": <b>".$fetchData['productName']."</b></span>
                        </div>
                        <div class='txt-center'>
                            <h3 class='txtRed bold'>"._tr('warning_operation_are_irreversible')."</h3>

                        </div>";
            $sendData = [];
            $sendData['title'] = _tr('remove_stock');
            $sendData['msg'] = $message;
            $sendData['url'] = _system.DS.$this->getModuleName().DS.'remove'.DS.$prdid.DS.System::getAccessToken();
            $sendData['method'] = 'GET';
            $sendData['type'] = 'confirm';

            echo json_encode($sendData);
        }
    }
}
