<?php
/**
 * Created by MarxMedia.
 * Author: Kevin Marques
 * Date: 08/07/2018 - 19:49
 * Grh : AddCredential.moduleodule
 */

namespace Modules\Application\Credentials\Manager;


use Modules\Auth;
use Modules\CNN;
use Modules\System;

class Chg
{
    private $sql;
    private $cidToEdit;
    private $accessToken;

    public function setAccessToken($accessToken) { $this->accessToken = $accessToken; }
    public function getAccessToken() { return $this->accessToken; }
    public function getCidToEdit() { return $this->cidToEdit; }
    public function setCidToEdit($cidToEdit) { $this->cidToEdit = $cidToEdit; }
    public function getSql() { return $this->sql; }
    public function __construct() {
        $this->sql = CNN::getSql();

    }
    public function init(){
        if(null == $this->getCidToEdit()){
            System::message('error',_tr('credentials'),_tr('cid_not_found'));
        }
        else if($this->getAccessToken() != System::getAccessToken()){
            System::message('error',_tr('credentials'),_tr('access_token_receive_is_wrong'));
        }
        else if(empty($_POST['username']) || empty($_POST['usergroup']) || $_POST['usergroup'] == 'none' || $_POST['username'] == 'none'){
            System::message('error',_tr('credentials'),_tr('all_credential_fields_need_to_be_filled'));
        }
        else{
            //Cria uma verificação de credenciais para verificar alterações
            $getData = $this->getSql()->query("SELECT * FROM ".__CREDENTIALS);
            $fetch = $getData->fetchAll(\PDO::FETCH_ASSOC);
            //Variavel comparativa
            $cidcombo = $_POST['username'].$_POST['usergroup'];
            //---------------------------
            $nothingchange = false;
            foreach ($fetch as $each) {
                if($each['cid'] == $cidcombo){
                    $nothingchange = true;
                    break;
                }
            }
            if($nothingchange){
                System::message("info",_tr('credentials'),_tr('nothing_was_changed'));
            }
            else{

                //----
                $editCred = $this->getSql()->prepare("UPDATE ".__CREDENTIALS." 
                SET cid=:newcid, guid=:guid,authid=:authid
                WHERE cid=:cid");
                $editCred->bindValue(":cid",$this->getCidToEdit());
                $editCred->bindValue(":newcid",$cidcombo);
                $editCred->bindValue(":authid",$_POST['username']);
                $editCred->bindValue(":guid",$_POST['usergroup']);
                $result = $editCred->execute();

                if ($result){
                    System::message("success",_tr('credentials'),_tr('credential_successfully_edited'));
                }
                else{
                    System::message("error",_tr('credentials'),_tr('error_on_add_user_group'));
                }
            }
        }
    }
}