<?php
/**
 * Created by MarxMedia.
 * Author: Kevin Marques
 * Date: 13/07/2018 - 10:22
 * Grh : GetDataCredential.moduleodule
 */

namespace Modules\Application\Credentials\Manager;


use Modules\CNN;
use Modules\System;

class GetData
{
    private $sql;
    private $moduleName;
    public function getSql() { return $this->sql; }
    public function getModuleName() { return $this->moduleName; }
    public function __construct($moduleName) {
        $this->sql = CNN::getSql();
        $this->moduleName = $moduleName;
    }
    public function getData($cid, $accessToken){
        if(empty($cid)){
            System::message('error',_tr('get_data'),_tr('group_id_needed_not_found'));
        }
        else if($accessToken != System::getAccessToken()){
            System::message('error',_tr('get_data'),_tr('access_token_receive_is_wrong'));
        }
        else{
            $recoverGroupName = $this->getSql()->prepare("SELECT * FROM see_credentials WHERE cid=?");
            $recoverGroupName->bindValue(1,$cid);
            $recoverGroupName->execute();
            $fetchData = $recoverGroupName->fetch(\PDO::FETCH_ASSOC);
            $groupName = $fetchData['usergroupname'];
            $username = $fetchData['username'];
            $message = "<div class='txt-center pd-tb-1'> 
                            <h3 class='txt-center'>"._tr('warning_credential_will_be_removed')."</h3>
                            <h4>"._tr('credential_id').": <b>".$fetchData['cid']."</b></h4>
                            <span class='block'>"._tr('user_name').": <b>".$fetchData['username']."</b></span>
                            <span class='block'>"._tr('user_group').": <b>".$fetchData['usergroupname']."</b></span>
                        </div>
                        <div class='txt-center'> 
                            <h3 class='txtRed bold'>"._tr('this_action_is_permanent_do_it')."</h3>
                            
                        </div>";
            $sendData = [];
            $sendData['title'] = _tr('remove_credential');
            $sendData['msg'] = $message;
            $sendData['url'] = _system.DS.$this->getModuleName().DS.'remove'.DS.$cid.DS.System::getAccessToken();
            $sendData['method'] = 'GET';
            $sendData['type'] = 'confirm';

            echo json_encode($sendData);
        }
    }
}