<?php

namespace Modules\Application\Category\GraphicInterface;

use Interfaces\ThrowableAll;
use Modules\CNN;
use Modules\System;
use Modules\Template\Template;
use Modules\Upshot;

class Home
{

	private $sql;

    public function getSql() { return $this->sql; }
    
    public function __construct($ModuleName) {
        try{
            $this->sql = CNN::getSql();
            $JsonParser =[];
            $DataParser=[];
            $DataParser['link_categories'] = WWW_PATH.$ModuleName."/new/";
            $DataParser['data_table'] = '';
            //

            $categories = $this->getSql()->query("SELECT * FROM category");
            if($categories->rowCount() > 0){
            	
                //Variavel de cabeçalho de tabela
                $tableHeadData = [];
                $tableHeadData['data_table'] ='';
                //Recupera o template de TR para inserção na tabela
                foreach ($categories->fetchAll(\PDO::FETCH_ASSOC) as $tableLine) {

                    $preLink = WWW_PATH . $ModuleName . DS;
                    //Data Parser de tratamento
                    $lineTable = [];
                    $lineTable['ctgid'] = $tableLine['ctgid'];
                    $lineTable['name'] = $tableLine['name'];
                    $lineTable['link_edit'] = $preLink . 'edit' . DS . $tableLine['ctgid'];
                    $dataPrompt = [];
                    $dataPrompt['url'] = _system . DS . $ModuleName . DS . 'get' . DS . $tableLine['ctgid'] . DS . System::getAccessToken();
                    $dataPrompt['method'] = "GET";
                    $lineTable['data_prompt'] = base64_encode(json_encode($dataPrompt));

                    $tempTr = new Template(APP_ROOT . DS . MODULES_PATH . DS . $ModuleName . DS . "Gui/Views/Controller/tableListCategories.tpl", $lineTable, true);
                    $tableHeadData['data_table'] .= $tempTr->showTemplate();
                   
                }
                //Template de cabeçalho e estrutura de tabela
                $TableHeader = new Template(APP_ROOT.DS.MODULES_PATH.DS.$ModuleName.DS."Gui/Views/Controller/tableCategories.tpl",$tableHeadData,true);
                //Composição de Template principal da página
                $DataParser['composition'] =$TableHeader->showTemplate();
            }
            else{
                $tableMessage = [];
                $tableMessage['title'] = _tr('no_categories_registered');
                $tableMessage['msg'] = _tr('none_one_categories_are_registered');
                $tableMessage['icon'] = 'ais-info';
                $TableNothing = new Template(APP_ROOT.DS.MODULES_PATH.DS.$ModuleName.DS."Gui/Views/Controller/tableNoContent.tpl",$tableMessage,true);
                $DataParser['composition'] = $TableNothing->showTemplate();
            }

            //Template principal da página
            $Template = new Template(APP_ROOT.DS.MODULES_PATH.DS.$ModuleName.DS."Gui/Views/basic.tpl",$DataParser,true);
            echo $Template->showTemplate();
        }
        catch (ThrowableAll $exception){
            Upshot::showData("Excessão",null,$exception->getMessage(),'',null,true);
        }

    }

}


?>