<?php
/**
 * Created by MarxMedia.
 * Author: Kevin Marques
 * Date: 08/07/2018 - 19:49
 * Grh : AddCredential.moduleodule
 */

namespace Modules\Application\Category\Manager;

use Modules\Auth;
use Modules\CNN;
use Modules\System;

class Add
{
    private $sql;
    private $accessToken;

    public function setAccessToken($accessToken) { $this->accessToken = $accessToken; }
    private function getAccessToken() { return $this->accessToken; }
    private function getSql() { return $this->sql; }
    public function __construct() {
        $this->sql = CNN::getSql();
    }
    public function init(){
        if(empty($_POST['name'])|| $_POST['name'] == 'none'){
            System::message('error',_tr('categories'),_tr('all_category_fields_need_to_be_filled'));
        }
        else if($this->getAccessToken() != System::getAccessToken()){
            System::message('error',_tr('categories'),_tr('access_token_receive_is_wrong').$this->getAccessToken());
        }
           
       
            else{
                $name = $_POST['name'];
                //----
                $addGroup = $this->getSql()->prepare("INSERT INTO category (name) 
                VALUES (:name)");
                $addGroup->bindValue(":name",$name);
                $result = $addGroup->execute();

                if ($result){
                    System::message("success",_tr('categories'),_tr('successfully_category_added'));
                }
                else{
                    System::message("error",_tr('categories'),_tr('error_on_add_category'));
                }
            
        }
    }
}