<?php

namespace Modules\Application\Category\Manager;


use Modules\Auth;
use Modules\CNN;
use Modules\System;

class Chg
{
    private $sql;
    private $ctgidToEdit;
    private $accessToken;

    public function setAccessToken($accessToken) { $this->accessToken = $accessToken; }
    public function getAccessToken() { return $this->accessToken; }
    public function getCtgidToEdit() { return $this->ctgidToEdit; }
    public function setCtgidToEdit($ctgidToEdit) { $this->ctgidToEdit = $ctgidToEdit; }
    public function getSql() { return $this->sql; }
    public function __construct() {
        $this->sql = CNN::getSql();

    }
    public function init(){
        if(null == $this->getCtgidToEdit()){
            System::message('error',_tr('categories'),_tr('cid_not_found'));
        }
        else if($this->getAccessToken() != System::getAccessToken()){
            System::message('error',_tr('categories'),_tr('access_token_receive_is_wrong'));
        }
        else if(empty($_POST['name']) || $_POST['name'] == 'none'){
            System::message('error',_tr('categories'),_tr('all_category_fields_need_to_be_filled'));
        }
        else{
           
      
                //----
                $editCred = $this->getSql()->prepare("UPDATE category 
                SET name=:name WHERE ctgid=:ctgid");
                $editCred->bindValue(":ctgid",$this->getCtgidToEdit());
                $editCred->bindValue(":name",$_POST['name']);
                $result = $editCred->execute();

                if ($result){
                    System::message("success",_tr('categories'),_tr('category_successfully_edited'));
                }
                else{
                    System::message("error",_tr('categories'),_tr('error_on_add_user_group'));
                }
          
        }
    }
}