<?php
/**
 * Created by MarxMedia.
 * Author: Kevin Marques
 * Date: 14/07/2018 - 19:04
 * Grh : DelGroup.module
 */

namespace Modules\Application\Category\Manager;


use Interfaces\ThrowableAll;
use Modules\CNN;
use Modules\System;

class Del
{
    private $accessToken;
    private $ctgidToRemove;
    private $sql;
    private $moduleName;

    public function setModuleName($moduleName) { $this->moduleName = $moduleName; }

    public function getModuleName() { return $this->moduleName; }
    public function setAccessToken($accessToken) { $this->accessToken = $accessToken; }
    public function setCtgidToRemove($ctgidToRemove) { $this->ctgidToRemove = $ctgidToRemove; }
    private function getCtgidToRemove() { return $this->ctgidToRemove; }
    private function getAccessToken() { return $this->accessToken; }

    public function getSql(): \PDO { return $this->sql; }
    public function __construct() {
        $this->sql= CNN::getSql();
    }
    public function remove(){
        try{
            if(null == $this->getCtgidToRemove()){
                System::message('error',_tr('remove_category'),_tr('cat_not_found'));
            }
            else if(System::getAccessToken() != $this->getAccessToken()){
                System::message('error',_tr('remove_category'),_tr('access_token_receive_is_wrong'));
            }
            else{
                !defined("_AUTHID") ? define("_AUTHID",$_SESSION['authid']) : null;
                $getCover = $this->getSql()->prepare("SELECT * FROM category WHERE ctgid=?");
                $getCover->bindValue(1,$this->getCtgidToRemove());
                $getCover->execute();
                $fetchCover = $getCover->fetch(\PDO::FETCH_ASSOC);
                //
                $getProductBinded = $this->getSql()->prepare("SELECT * FROM ".__PRODUCT." WHERE ctgid=?");
                $getProductBinded->bindValue(1,$this->getCtgidToRemove());
                $getProductBinded->execute();
                //
                
                if($getCover->rowCount() == 0){
                    System::message('error',_tr('remove_category'),_tr('cid_not_registered'));
                }
                else if($getProductBinded->rowCount() > 0){
                    System::message('error',_tr('remove_category'),_tr('cannot_remove_category_with_binded_products'));
                }
                else{
                    $remove = $this->getSql()->prepare("DELETE FROM category WHERE ctgid=?");
                    $remove->bindValue(1,$this->getCtgidToRemove());
                    $remove->execute();

                    if($remove){
                        System::message('success',_tr('remove_category'),_tr('category_successfully_removed'),System::goTo(WWW_PATH.$this->getModuleName(),1));
                    }
                    else{
                       System::message('warning',_tr('remove_category'),_tr('impossible_to_remove_category'));
                    }
                }
            }
        }
        catch (ThrowableAll $e){
            System::message('error',_tr('internal_error'),$e->getMessage());
        }
    }
}