<?php
/**
 * Created by MarxMedia.
 * Author: Kevin Marques
 * Date: 13/07/2018 - 10:22
 * Grh : GetDataCredential.moduleodule
 */

namespace Modules\Application\Category\Manager;


use Modules\CNN;
use Modules\System;

class GetData
{
    private $sql;
    private $moduleName;
    public function getSql() { return $this->sql; }
    public function getModuleName() { return $this->moduleName; }
    public function __construct($moduleName) {
        $this->sql = CNN::getSql();
        $this->moduleName = $moduleName;
    }
    public function getData($ctgid, $accessToken){
        if(empty($ctgid)){
            System::message('error',_tr('get_data'),_tr('group_id_needed_not_found'));
        }
        else if($accessToken != System::getAccessToken()){
            System::message('error',_tr('get_data'),_tr('access_token_receive_is_wrong'));
        }
        else{
            $recoverGroupName = $this->getSql()->prepare("SELECT * FROM category WHERE ctgid=?");
            $recoverGroupName->bindValue(1,$ctgid);
            $recoverGroupName->execute();
            $fetchData = $recoverGroupName->fetch(\PDO::FETCH_ASSOC);
            
            $sendData = [];
            $sendData['title'] = _tr('remove_category');
          //  $sendData['msg'] = $message;
            //echo getModuleName(); die();
            $sendData['url'] = _system.DS.'Category'.DS.'remove'.DS.$ctgid.DS.System::getAccessToken();
            $sendData['method'] = 'GET';
            $sendData['type'] = 'confirm';

            echo json_encode($sendData);
        }
    }
}