<?php
/**
 * Created by MarxMedia.
 * Author: Kevin Marques
 * Date: 07/07/2018 - 11:38
 * Grh : Credentialstials.module
 */

namespace Modules\Application\Credentials\GraphicInterface;

use Interfaces\ThrowableAll;
use Modules\CNN;
use Modules\System;
use Modules\Template\Template;
use Modules\Upshot;

class Home
{
    private $sql;

    public function getSql() { return $this->sql; }
    public function __construct($ModuleName) {
        try{
            $this->sql = CNN::getSql();
            $JsonParser =[];
            $DataParser=[];
            $DataParser['link_credentials'] = WWW_PATH.$ModuleName."/new/";
            $DataParser['data_table'] = '';
            //
            $getUserGroups = $this->getSql()->query("SELECT * FROM see_credentials WHERE groupactive = '1'");
            if($getUserGroups->rowCount() > 0){
                //Variavel de cabeçalho de tabela
                $tableHeadData = [];
                $tableHeadData['data_table'] ='';
                //Recupera o template de TR para inserção na tabela
                foreach ($getUserGroups->fetchAll(\PDO::FETCH_ASSOC) as $tableLine) {
                    if ($tableLine['userstatus'] != 4) {
                        $userStatus = '';
                        //1= ativo, 2=bloqueado, 3=inativo, 4=superusuarios
                        if ($tableLine['userstatus'] == 1) {
                            $userStatus = _tr('actived');
                        } else if ($tableLine['userstatus'] == 2) {
                            $userStatus = _tr('blocked');
                        } else if ($tableLine['userstatus'] == 3) {
                            $userStatus = _tr('inactive');
                        }

                        $preLink = WWW_PATH . $ModuleName . DS;
                        //Data Parser de tratamento
                        $lineTable = [];
                        $lineTable['cid'] = $tableLine['cid'];
                        $lineTable['guid'] = $tableLine['guid'];
                        $lineTable['user_group_name'] = $tableLine['usergroupname'];
                        $lineTable['name'] = $tableLine['username'];
                        $lineTable['user_status'] = $userStatus;
                        $lineTable['link_edit'] = $preLink . 'edit' . DS . $tableLine['cid'];
                        $dataPrompt = [];
                        $dataPrompt['url'] = _system . DS . $ModuleName . DS . 'get' . DS . $tableLine['cid'] . DS . System::getAccessToken();
                        $lineTable['data_prompt'] = base64_encode(json_encode($dataPrompt));
                        $tempTr = new Template(APP_ROOT . DS . MODULES_PATH . DS . $ModuleName . DS . "Gui/Views/Controller/tableListCredentials.tpl", $lineTable, true);
                        $tableHeadData['data_table'] .= $tempTr->showTemplate();
                    }
                }
                //Template de cabeçalho e estrutura de tabela
                $TableHeader = new Template(APP_ROOT.DS.MODULES_PATH.DS.$ModuleName.DS."Gui/Views/Controller/tableCredentials.tpl",$tableHeadData,true);
                //Composição de Template principal da página
                $DataParser['composition'] =$TableHeader->showTemplate();
            }
            else{
                $tableMessage = [];
                $tableMessage['title'] = _tr('no_credentials_registered');
                $tableMessage['msg'] = _tr('none_one_credentials_are_defined_to_users').'<br/><br/>'._tr('remember_super_user_not_shows_in_credential_table');
                $tableMessage['icon'] = 'ais-info';
                $TableNothing = new Template(APP_ROOT.DS.MODULES_PATH.DS.$ModuleName.DS."Gui/Views/Controller/tableNoContent.tpl",$tableMessage,true);
                $DataParser['composition'] = $TableNothing->showTemplate();
            }

            //Template principal da página
            $Template = new Template(APP_ROOT.DS.MODULES_PATH.DS.$ModuleName.DS."Gui/Views/basic.tpl",$DataParser,true);
            echo $Template->showTemplate();
        }
        catch (ThrowableAll $exception){
            Upshot::showData("Excessão",null,$exception->getMessage(),'',null,true);
        }

    }

}