<?php
/**
 * Created by MarxMedia.
 * Author: Kevin Marques
 * Date: 08/07/2018 - 00:53
 * Grh : NewCredentials.modulele
 */

namespace Modules\Application\Credentials\GraphicInterface;


use Interfaces\ThrowableAll;
use Modules\Auth;
use Modules\CNN;
use Modules\System;
use Modules\Template\Template;

class Modify
{
    private $cidToEdit;
    private $moduleName;
    private $sql;
    private function getSql(): \PDO { return $this->sql; }
    private function getCidToEdit() { return $this->cidToEdit; }
    private function getModuleName() { return $this->moduleName; }
    public function setCidToEdit($cidToEdit) { $this->cidToEdit = $cidToEdit; }
    public function setModuleName($moduleName) { $this->moduleName = $moduleName; }
    public function __construct($ModuleName,$guid) {
        $this->sql = CNN::getSql();
        $this->setModuleName($ModuleName);
        $this->setCidToEdit($guid);
    }
    public function init(){
        try{
            //Recuperando grupo para edição
            $userGroup = $this->getSql()->prepare("SELECT * FROM ".__CREDENTIALS." WHERE cid=?");
            $userGroup->bindValue(1,$this->getCidToEdit());
            $userGroup->execute();
            $fetchAllData = $userGroup->fetch(\PDO::FETCH_ASSOC);

            $datasend =[];
            $datasend['url'] = _system.DS.$this->getModuleName().DS."edit".DS.$this->getCidToEdit().DS.System::getAccessToken();
            $datasend['method'] = "POST";
            //-----------
            $Parser = [];
            $Parser['user_options'] ='';
            $Parser['user_group_options']='';
            //Edição de Permissoes
            //-------------
            //Recupera as configurações atuais
            $cidDefActual = $this->getSql()->prepare("SELECT * FROM ".__CREDENTIALS." WHERE cid=?");
            $cidDefActual->bindValue(1,$this->getCidToEdit());
            $cidDefActual->execute();
            $ftCidActual = $cidDefActual->fetch(\PDO::FETCH_ASSOC);
            //Recupera a lista de usuário
            $users = $this->getSql()->prepare("SELECT * FROM ".__USERS." WHERE authid=?");
            $users->bindValue(1,$ftCidActual['authid']);
            $users->execute();
            $ftUsers = $users->fetch(\PDO::FETCH_ASSOC);
            //Recuperação de lista de grupo de usuário
            $groups = $this->getSql()->query("SELECT * FROM see_usergroups");
            $ftGroups = $groups->fetchAll(\PDO::FETCH_ASSOC);

            //Atribuição de options do select
            $name = $ftUsers['name'].' '.$ftUsers['lastname'];
            $Parser['user_options'] .= "<option value='".$ftCidActual['authid']."' selected='selected'>".$name."</option>";

            foreach ($ftGroups as $ftGroup) {
                $selectedGuid = $ftGroup['guid'] == $ftCidActual['guid'] ? "selected='selected'" : '';
                $Parser['user_group_options'] .= "<option value='".$ftGroup['guid']."'  ".$selectedGuid.">".$ftGroup['name']."</option>";
            }
            //Default patterns
            $Parser['link_back'] = WWW_PATH.$this->getModuleName().DS;
            $Parser['datasend'] = 'data-send="'.base64_encode(json_encode($datasend)).'"';
            $template = new Template(APP_ROOT.DS.MODULES_PATH.DS.$this->getModuleName().DS."Gui/Views/editCredential.tpl",$Parser,true);
            echo $template->showTemplate();
        }
        catch (ThrowableAll $exception){
            echo $exception->getMessage();
        }

    }
}