<?php
/**
 * Created by MarxMedia Solutions.
 *         Author: Nelson Anjos
 *    Date: 03/2019
 *
 */

namespace Modules\Transaction;

use Modules\CNN;
use Modules\Data;
use Modules\System;

class Output
{
    private $sql;
    private $accessToken;
    

    public function setAccessToken($accessToken) { $this->accessToken = $accessToken; }
    private function getAccessToken() { return $this->accessToken; }
    private function getSql() { return $this->sql; }
    public function __construct() {
        $this->sql = CNN::getSql();
    }
    public function init(){
       
        
        //Verifica se tem campos vazios
        if($_POST['productName'] == 'none' || empty($_POST['productQuantity']) == 'none'){
            System::message('error',_tr('transaction_input'),_tr('all_trasaction_fields_need_to_be_filled'));
        }

        //Se não verifica se tem acesso
        else if($this->getAccessToken() != System::getAccessToken()){
            System::message('error',_tr('transaction_input'),_tr('access_token_receive_is_wrong').$this->getAccessToken());
        }
        else{
    
            $getData = $this->getSql()->query("SELECT * FROM see_stocks WHERE productName = '".$_POST['productName']."'");
            $getData->execute();
            $fetch = $getData->fetch(\PDO::FETCH_ASSOC);
            $prdid = $fetch['prdid'];
            
            if($fetch['quantity'] < $_POST['productQuantity']){
                System::message('error',_tr('transaction_input'),sprintf(_tr('you_cannot_get_out_more_than_have'),$fetch['quantity']));
            }
            else{
                //Compara o nome na tabela de produtos para pegar o id
                $input = $this->getSql()->prepare("UPDATE ".__STOCK." SET quantity = quantity - :quantity WHERE prdid = :prdid");
                $input->bindValue(':prdid',$prdid);
                $input->bindValue(':quantity',$_POST['productQuantity']);
                $result = $input->execute();
    
                if ($result){
                    $protocol = new System();
                    $protocol->setAccessToken();
                    
                    $input = $this->getSql()->prepare("INSERT INTO ".__TRANSACTIONS." (protocol, prdid, quantity, dateOperation, typeAction) VALUES (?,?,?,?,?)");
                    $input->bindValue(1,$protocol->getAccessToken());
                    $input->bindValue(2,$prdid);
                    $input->bindValue(3,$_POST['productQuantity']);
                    $input->bindValue(4, Data::setData(true));
                    $input->bindValue(5,0);
                    $result = $input->execute();
                    if($result){
                        System::message("success",_tr('transaction_output'),_tr('successfully_transaction_output_added'));
                    } else {
                        System::message("Erro",_tr('Registrar Transação'),_tr('Ocorreu um erro ao registrar a transação!'));
                    }
                }
                else{
                    System::message("error",_tr('transaction_output'),_tr('error_on_output_transaction'));
                }
            }
            
          }
          }
        }
