<?php
/**
 * Created by MarxMedia.
 * Author: Kevin Marques
 * Date: 14/07/2018 - 19:04
 * Grh : DelGroup.module
 */

namespace Modules\Application\UserGroup\Manager;


use Interfaces\ThrowableAll;
use Modules\CNN;
use Modules\System;

class Del
{
    private $accessToken;
    private $guidToRemove;
    private $sql;
    private $moduleName;

    public function setModuleName($moduleName) { $this->moduleName = $moduleName; }

    public function getModuleName() { return $this->moduleName; }
    public function setAccessToken($accessToken) { $this->accessToken = $accessToken; }
    public function setGuidToRemove($guidToRemove) { $this->guidToRemove = $guidToRemove; }
    private function getGuidToRemove() { return $this->guidToRemove; }
    private function getAccessToken() { return $this->accessToken; }

    public function getSql(): \PDO { return $this->sql; }
    public function __construct() {
        $this->sql= CNN::getSql();
        !defined("_AUTHID") ? define("_AUTHID",$_SESSION['authid']) : null;
    }
    public function remove(){
        try{
            if(null == $this->getGuidToRemove()){
                System::message('error',_tr('remove_user_group'),_tr('guid_not_found'));
            }
            else if(System::getAccessToken() != $this->getAccessToken()){
                System::message('error',_tr('remove_user_group'),_tr('access_token_receive_is_wrong'));
            }
            else{
                $getCover = $this->getSql()->prepare("SELECT * FROM see_usergroups WHERE guid=?");
                $getCover->bindValue(1,$this->getGuidToRemove());
                $getCover->execute();
                //Verifica se o usuário atual esta utilizando do grupo de usuário em questão
                $checkUser = $this->getSql()->prepare("SELECT * FROM see_permissions WHERE authid=:authid");
                $checkUser->bindValue(":authid",_AUTHID);
                $checkUser->execute();
                $fetchCheck = $checkUser->fetch(\PDO::FETCH_ASSOC);
                if($getCover->rowCount() == 0){
                    System::message('error',_tr('remove_user_group'),_tr('guid_not_registered'));
                }
                else if($fetchCheck['guid'] == $this->getGuidToRemove()){
                    System::message('error',_tr('remove_user_group'),_tr('you_cannot_remove_user_group_that_is_in_use'));
                }
                else{
                    $remove = $this->getSql()->prepare("DELETE FROM ".__USERGROUP." WHERE guid=?");
                    $remove->bindValue(1,$this->getGuidToRemove());
                    $remove->execute();

                    if($remove){
                        System::message('success',_tr('remove_user_group'),_tr('user_group_successfully_removed'),System::goTo(WWW_PATH.$this->getModuleName(),1));
                    }
                    else{
                        System::message('warning',_tr('remove_user_group'),_tr('impossible_to_remove_user_group'));
                    }
                }
            }
        }
        catch (ThrowableAll $e){
            System::message('error',_tr('internal_error'),$e->getMessage());
        }
    }
}