<?php


namespace Modules\Application\Products\GraphicInterface;


use Interfaces\ThrowableAll;
use Modules\Auth;
use Modules\CNN;
use Modules\System;
use Modules\Template\Template;

class Modify
{
    private $prdidToEdit;
    private $moduleName;
    private $sql;
    private function getSql(): \PDO { return $this->sql; }
    private function getPrdidToEdit() { return $this->prdidToEdit; }
    private function getModuleName() { return $this->moduleName; }
    public function setPrdidToEdit($prdidToEdit) { $this->prdidToEdit = $prdidToEdit; }
    public function setModuleName($moduleName) { $this->moduleName = $moduleName; }
    public function __construct($ModuleName,$guid) {
        $this->sql = CNN::getSql();
        $this->setModuleName($ModuleName);
        $this->setPrdidToEdit($guid);
    }
    public function init(){
        try{
            
            $datasend =[];
            $datasend['url'] = _system.DS.$this->getModuleName().DS."edit".DS.$this->getPrdidToEdit().DS.System::getAccessToken();
            $datasend['method'] = "POST";
            //-----------
            $Parser = [];
            $Parser['user_options'] ='';
            $Parser['user_group_options']='';
            //Edição de Permissoes
            //-------------
            //Recupera as configurações atuais
            $cidDefActual = $this->getSql()->prepare("SELECT * FROM ".__PRODUCT." WHERE prdid=?");
            $cidDefActual->bindValue(1,$this->getPrdidToEdit());
            $cidDefActual->execute();
            $ftCidActual = $cidDefActual->fetch(\PDO::FETCH_ASSOC);

           $nomeProduto = $ftCidActual["name"];
            $Parser['prod_name'] = $nomeProduto;

            $groups = $this->getSql()->query("SELECT * FROM ".__CATEGORY);
            $ftGroups = $groups->fetchAll(\PDO::FETCH_ASSOC);
            $Parser['category_options'] ='';
            foreach ($ftGroups as $ftGroup) {
                $Parser['category_options'] .= "<option value='".$ftGroup['ctgid']."'>".$ftGroup['name']."</option>";
            }
          
            //Default patterns
            $Parser['link_back'] = WWW_PATH.$this->getModuleName().DS;
            $Parser['datasend'] = 'data-send="'.base64_encode(json_encode($datasend)).'"';
            $template = new Template(APP_ROOT.DS.MODULES_PATH.DS.$this->getModuleName().DS."Gui/Views/editProducts.tpl",$Parser,true);
            echo $template->showTemplate();
        }
        catch (ThrowableAll $exception){
            echo $exception->getMessage();
        }

    }
}